import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { AngelNumber } from "../types/angel-number";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, "..");
const sourceDir = path.join(rootDir, "data", "angel-numbers", "source", "en");
const outputFile = path.join(rootDir, "data", "angel-numbers", "generated.ts");

function assertString(value: unknown, field: string): asserts value is string {
  if (typeof value !== "string" || value.trim().length === 0) {
    throw new Error(`${field} must be a non-empty string`);
  }
}

function validateAngelNumber(item: AngelNumber) {
  assertString(item.number, "number");
  assertString(item.slug, "slug");
  assertString(item.title, "title");
  assertString(item.summary, `${item.slug}.summary`);

  if (item.slug !== item.number) {
    throw new Error(`${item.slug} slug must match number`);
  }

  if (item.meta.description.length < 120) {
    throw new Error(`${item.slug} meta description is too short`);
  }

  if (item.faqs.length < 3) {
    throw new Error(`${item.slug} must include at least 3 FAQs`);
  }

  if (item.relatedNumbers.length < 3) {
    throw new Error(`${item.slug} must include at least 3 related numbers`);
  }
}

async function main() {
  const filenames = (await readdir(sourceDir))
    .filter((filename) => filename.endsWith(".json"))
    .sort((a, b) => Number.parseInt(a, 10) - Number.parseInt(b, 10));

  const items = await Promise.all(
    filenames.map(async (filename) => {
      const raw = await readFile(path.join(sourceDir, filename), "utf8");
      const item = JSON.parse(raw) as AngelNumber;
      validateAngelNumber(item);
      return item;
    }),
  );

  const slugs = new Set<string>();
  for (const item of items) {
    if (slugs.has(item.slug)) {
      throw new Error(`Duplicate angel number slug: ${item.slug}`);
    }
    slugs.add(item.slug);
  }

  const moduleText = `// Generated by scripts/build-angel-number-data.ts. Do not edit manually.
import type { AngelNumber } from "@/types/angel-number";

export const ANGEL_NUMBERS: AngelNumber[] = ${JSON.stringify(items, null, 2)};
`;

  await writeFile(outputFile, moduleText);
  console.log(`Generated ${items.length} angel number records.`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
