import fs from "fs";
import path from "path";
import matter from "gray-matter";

type SerializedPost = Record<string, unknown> & {
  content: string;
  locale: string;
  slug: string;
};

const BLOGS_DIR = path.join(process.cwd(), "blogs");
const OUTPUT_FILE = path.join(process.cwd(), "lib", "cms", "blog-data.ts");

function normalizeSlug(value: unknown, fallback: string) {
  const slug = typeof value === "string" && value.trim() ? value : fallback;
  return slug.replace(/^\//, "").replace(/\/$/, "");
}

function readLocalePosts(locale: string) {
  const localeDir = path.join(BLOGS_DIR, locale);
  if (!fs.existsSync(localeDir)) {
    return [];
  }

  return fs
    .readdirSync(localeDir)
    .filter((filename) => /\.(md|mdx)$/.test(filename))
    .reverse()
    .map((filename): SerializedPost => {
      const fullPath = path.join(localeDir, filename);
      const fileContents = fs.readFileSync(fullPath, "utf8");
      const { data, content } = matter(fileContents);
      const fallbackSlug = filename.replace(/\.(md|mdx)$/, "");

      return {
        ...data,
        locale,
        slug: normalizeSlug(data.slug, fallbackSlug),
        content,
      };
    });
}

function generateBlogData() {
  if (!fs.existsSync(BLOGS_DIR)) {
    return {};
  }

  return fs
    .readdirSync(BLOGS_DIR)
    .filter((entry) => fs.statSync(path.join(BLOGS_DIR, entry)).isDirectory())
    .sort()
    .reduce<Record<string, SerializedPost[]>>((acc, locale) => {
      acc[locale] = readLocalePosts(locale);
      return acc;
    }, {});
}

function writeTypeScriptFile(data: Record<string, SerializedPost[]>) {
  const serialized = JSON.stringify(data, null, 2).replace(/</g, "\\u003c");
  const source = `// This file is generated by scripts/build-blog-data.ts. Do not edit by hand.
export const blogData = ${serialized} as const;

export type BlogData = typeof blogData;
`;

  fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
  fs.writeFileSync(OUTPUT_FILE, source);
}

writeTypeScriptFile(generateBlogData());
console.log(`Generated ${path.relative(process.cwd(), OUTPUT_FILE)}`);
